name: SpikyBot Code Agent

on:
  issues: { types: [opened] }
  issue_comment: { types: [created] }
  pull_request: { types: [opened] }
  pull_request_review: { types: [submitted] }

jobs:
  spikybot:
    runs-on: ubuntu-latest
    if: ${{ github.event.sender.login != 'spikybot' && contains(github.event.comment.body || github.event.issue.body || github.event.pull_request.body, '@spikybot') }}
    steps:
      - uses: spikybot/spikybot@main
        with:
          codex-token: ${{ secrets.CODEX_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
